global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-a'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-a:8080']
  
  - job_name: 'service-b'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-b:8081']
  
  - job_name: 'service-c'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-c:8082']
  
  - job_name: 'service-d'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-d:8083']
